name: Build an RC artifact

on:
  workflow_dispatch:
    artifact_name:
      description: Name of the artifact to promote
      required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.inputs.artifact_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: release_${{ github.event.inputs.artifact_name }}
          path: ${{ github.event.inputs.artifact_name }}