name: Promote RC to Release

on:
  workflow_dispatch:
    inputs:
      rc_version:
        description: RC version
        required: true
      artifact_name:
        description: Name of the artifact to promote
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-release-candidate.yml
          name: ${{ github.event.inputs.artifact_name }}
          check_artifacts: true

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: release_${{ github.event.inputs.artifact_name }}
          path: ${{ github.event.inputs.artifact_name }}

      - name: Configure git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "kevvlvl@users.noreply.github.com"

      - name: Tag a release
        run: |
          
          echo "Tag a release"
          
          releaseVersion="release_${{ github.event.inputs.rc_version }}"
          
          echo "Release to be tagged [$releaseVersion]"
          git tag -a $releaseVersion -m "release ver"
          git push origin main $releaseVersion